// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dTerm.Infra.EfCore;

namespace dTerm.Infra.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210322012426_CreateInitialSchema")]
    partial class CreateInitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("dTerm.Domain.ProcessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessExecutablePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessStartupArgs")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<byte>("ProcessType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UTCCreation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Consoles");
                });
#pragma warning restore 612, 618
        }
    }
}
