// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dTerm.Infra.EfCore;

namespace dTerm.Infra.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("dTerm.Domain.ProcessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessExecutablePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessStartupArgs")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<byte>("ProcessType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UTCCreation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Consoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("036c0c75-2509-4114-976e-0c123b80ad55"),
                            Icon = "Console",
                            Name = "Command Promp",
                            OrderIndex = 1,
                            ProcessExecutablePath = "cmd.exe",
                            ProcessStartupArgs = "",
                            ProcessType = (byte)1,
                            UTCCreation = new DateTime(2021, 3, 22, 1, 25, 22, 565, DateTimeKind.Utc).AddTicks(2020)
                        },
                        new
                        {
                            Id = new Guid("5de39ac0-296f-423c-97f1-6ee71b7a4b2d"),
                            Icon = "Git",
                            Name = "Git Bash",
                            OrderIndex = 2,
                            ProcessExecutablePath = "git-bash.exe",
                            ProcessStartupArgs = "--login -i",
                            ProcessType = (byte)1,
                            UTCCreation = new DateTime(2021, 3, 22, 1, 25, 22, 565, DateTimeKind.Utc).AddTicks(2634)
                        },
                        new
                        {
                            Id = new Guid("4e6d5d59-d537-4b66-aa97-1bd066dde1fe"),
                            Icon = "Powershell",
                            Name = "Power Shell",
                            OrderIndex = 3,
                            ProcessExecutablePath = "powershell.exe",
                            ProcessStartupArgs = "",
                            ProcessType = (byte)1,
                            UTCCreation = new DateTime(2021, 3, 22, 1, 25, 22, 565, DateTimeKind.Utc).AddTicks(2643)
                        },
                        new
                        {
                            Id = new Guid("a460e3b0-278e-4328-bc5b-16f5a7eb1f27"),
                            Icon = "Linux",
                            Name = "WSL Default Shel",
                            OrderIndex = 4,
                            ProcessExecutablePath = "wsl.exe",
                            ProcessStartupArgs = "",
                            ProcessType = (byte)1,
                            UTCCreation = new DateTime(2021, 3, 22, 1, 25, 22, 565, DateTimeKind.Utc).AddTicks(2647)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
